services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: oms

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: oms
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 2s
      timeout: 2s
      retries: 30

  tests:
    build: ./tests
    volumes:
      - ./tests:/tests
    environment:
      BASE_URL: http://api:8000
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: oms_test
      MONGO_ORDERS_COLLECTION: orders
      TOKEN: ""
    working_dir: /tests
    command: pytest -q -s
    depends_on:
      api:
        condition: service_healthy
      mongo:
        condition: service_started